export const nouns = [
  // Food & Drink
  { en: 'apple', pl: 'jabłko', hint: 'zielone' },
  { en: 'banana', pl: 'banan', hint: 'żółty' },
  { en: 'bread', pl: 'chleb', hint: 'piekarnia' },
  { en: 'butter', pl: 'masło', hint: 'żółte' },
  { en: 'cake', pl: 'tort', hint: 'urodziny' },
  { en: 'carrot', pl: 'marchew', hint: 'pomarańczowa' },
  { en: 'cheese', pl: 'ser', hint: 'mleko' },
  { en: 'chicken', pl: 'kurczak', hint: 'pieczony' },
  { en: 'chocolate', pl: 'czekolada', hint: 'słodka' },
  { en: 'coffee', pl: 'kawa', hint: 'czarna' },
  { en: 'egg', pl: 'jajko', hint: 'kurza' },
  { en: 'fish', pl: 'ryba', hint: 'woda' },
  { en: 'fork', pl: 'widelec', hint: 'kolce' },
  { en: 'glass', pl: 'szklanka', hint: 'przezroczysty' },
  { en: 'grape', pl: 'winogrono', hint: 'winogród' },
  { en: 'ham', pl: 'szynka', hint: 'mięso' },
  { en: 'honey', pl: 'miód', hint: 'pszczoła' },
  { en: 'ice cream', pl: 'lody', hint: 'zimne' },
  { en: 'knife', pl: 'nóż', hint: 'ostre' },
  { en: 'lemon', pl: 'cytryna', hint: 'kwaśny' },
  { en: 'lettuce', pl: 'sałata', hint: 'zielona' },
  { en: 'lime', pl: 'limonka', hint: 'zielony' },
  { en: 'milk', pl: 'mleko', hint: 'białe' },
  { en: 'mushroom', pl: 'grzyb', hint: 'las' },
  { en: 'olive', pl: 'oliwka', hint: 'zielona' },
  { en: 'onion', pl: 'cebula', hint: 'łzy' },
  { en: 'orange', pl: 'pomarańcza', hint: 'pomarańczowy' },
  { en: 'pasta', pl: 'makaron', hint: 'włoski' },
  { en: 'peach', pl: 'brzoskwinia', hint: 'fuzzy' },
  { en: 'pear', pl: 'gruszka', hint: 'kształt' },
  { en: 'pepper', pl: 'pieprz', hint: 'pikantny' },
  { en: 'pizza', pl: 'pizza', hint: 'ser' },
  { en: 'plate', pl: 'talerz', hint: 'ceramika' },
  { en: 'plum', pl: 'śliwka', hint: 'fioletowa' },
  { en: 'rice', pl: 'ryż', hint: 'białe' },
  { en: 'salad', pl: 'sałata', hint: 'zdrowa' },
  { en: 'salt', pl: 'sól', hint: 'biała' },
  { en: 'sandwich', pl: 'kanapka', hint: 'chleb' },
  { en: 'sauce', pl: 'sos', hint: 'pomidorowy' },
  { en: 'soup', pl: 'zupa', hint: 'gorąca' },
  { en: 'spoon', pl: 'łyżka', hint: 'metal' },
  { en: 'sugar', pl: 'cukier', hint: 'słodki' },
  { en: 'tea', pl: 'herbata', hint: 'gorący' },
  { en: 'tomato', pl: 'pomidor', hint: 'czerwony' },
  { en: 'water', pl: 'woda', hint: 'czysty' },
  { en: 'wheat', pl: 'pszenica', hint: 'pole' },
  { en: 'wine', pl: 'wino', hint: 'czerwone' },
  { en: 'yogurt', pl: 'jogurt', hint: 'gęsty' },
  { en: 'zucchini', pl: 'cukinia', hint: 'zielony' },

  // Animals
  { en: 'ant', pl: 'mrówka', hint: 'kolonia' },
  { en: 'bat', pl: 'nietoperz', hint: 'noc' },
  { en: 'bear', pl: 'niedźwiedź', hint: 'miód' },
  { en: 'bee', pl: 'pszczoła', hint: 'miód' },
  { en: 'bird', pl: 'ptak', hint: 'latający' },
  { en: 'buffalo', pl: 'bizon', hint: 'rogi' },
  { en: 'butterfly', pl: 'motyl', hint: 'skrzydła' },
  { en: 'camel', pl: 'wielbłąd', hint: 'garb' },
  { en: 'cat', pl: 'kot', hint: 'mruczeć' },
  { en: 'cheetah', pl: 'gepard', hint: 'szybkość' },
  { en: 'chicken', pl: 'kura', hint: 'kokodak' },
  { en: 'cow', pl: 'krowa', hint: 'mleko' },
  { en: 'crocodile', pl: 'krokodyl', hint: 'zęby' },
  { en: 'deer', pl: 'jeleń', hint: 'poroża' },
  { en: 'dog', pl: 'pies', hint: 'sierść' },
  { en: 'dolphin', pl: 'delfin', hint: 'czysty' },
  { en: 'donkey', pl: 'osioł', hint: 'uparty' },
  { en: 'eagle', pl: 'orzeł', hint: 'szybki' },
  { en: 'elephant', pl: 'słoń', hint: 'trąba' },
  { en: 'fish', pl: 'ryba', hint: 'łuski' },
  { en: 'fox', pl: 'lis', hint: 'chytry' },
  { en: 'frog', pl: 'żaba', hint: 'skakanie' },
  { en: 'giraffe', pl: 'żyrafa', hint: 'długa' },
  { en: 'goat', pl: 'koza', hint: 'rogi' },
  { en: 'gorilla', pl: 'goryl', hint: 'siła' },
  { en: 'hamster', pl: 'chomik', hint: 'mały' },
  { en: 'hedgehog', pl: 'jeż', hint: 'kolce' },
  { en: 'hippo', pl: 'hipopotam', hint: 'woda' },
  { en: 'horse', pl: 'koń', hint: 'jeźdźcy' },
  { en: 'kangaroo', pl: 'kangur', hint: 'australijski' },
  { en: 'koala', pl: 'koala', hint: 'eukaliptus' },
  { en: 'leopard', pl: 'leopard', hint: 'plamy' },
  { en: 'lion', pl: 'lew', hint: 'grzywka' },
  { en: 'lizard', pl: 'jaszczurka', hint: 'zwinna' },
  { en: 'lobster', pl: 'homar', hint: 'pazury' },
  { en: 'monkey', pl: 'małpa', hint: 'banany' },
  { en: 'moose', pl: 'łoś', hint: 'większy' },
  { en: 'mouse', pl: 'mysz', hint: 'mała' },
  { en: 'octopus', pl: 'ośmiornica', hint: 'ramiona' },
  { en: 'owl', pl: 'sowa', hint: 'nocna' },
  { en: 'panda', pl: 'panda', hint: 'bambusowy' },
  { en: 'parrot', pl: 'papuga', hint: 'kolorowy' },
  { en: 'peacock', pl: 'paw', hint: 'pióra' },
  { en: 'penguin', pl: 'pingwin', hint: 'lód' },
  { en: 'pig', pl: 'świnia', hint: 'błoto' },
  { en: 'pigeon', pl: 'gołąb', hint: 'gołębie' },
  { en: 'porcupine', pl: 'jeżozwierz', hint: 'igły' },
  { en: 'rabbit', pl: 'królik', hint: 'uszy' },
  { en: 'raccoon', pl: 'szop pracz', hint: 'maska' },
  { en: 'raven', pl: 'kruk', hint: 'czarny' },
  { en: 'rhinoceros', pl: 'nosorożec', hint: 'róg' },
  { en: 'seal', pl: 'foka', hint: 'lód' },
  { en: 'shark', pl: 'rekin', hint: 'żarłoczny' },
  { en: 'sheep', pl: 'owca', hint: 'wełna' },
  { en: 'snake', pl: 'wąż', hint: 'żaden' },
  { en: 'sparrow', pl: 'wróbel', hint: 'mały' },
  { en: 'spider', pl: 'pająk', hint: 'pajęczyna' },
  { en: 'squirrel', pl: 'wiewiórka', hint: 'orzechy' },
  { en: 'stork', pl: 'bocian', hint: 'dzieci' },
  { en: 'swan', pl: 'łabędź', hint: 'biały' },
  { en: 'tiger', pl: 'tygrys', hint: 'paski' },
  { en: 'tortoise', pl: 'żółw', hint: 'powolny' },
  { en: 'toucan', pl: 'tukan', hint: 'dziób' },
  { en: 'turkey', pl: 'indyk', hint: 'dziękczynienie' },
  { en: 'turtle', pl: 'żółw', hint: 'skorupa' },
  { en: 'vulture', pl: 'sęp', hint: 'padlina' },
  { en: 'walrus', pl: 'mors', hint: 'kły' },
  { en: 'whale', pl: 'wieloryb', hint: 'ocean' },
  { en: 'wolf', pl: 'wilk', hint: 'wycie' },
  { en: 'zebra', pl: 'zebra', hint: 'paski' },

  // Objects & Tools
  { en: 'anchor', pl: 'kotwica', hint: 'statek' },
  { en: 'axe', pl: 'siekiera', hint: 'drewno' },
  { en: 'backpack', pl: 'plecak', hint: 'podróż' },
  { en: 'badge', pl: 'odznaka', hint: 'haft' },
  { en: 'bag', pl: 'torba', hint: 'noszenie' },
  { en: 'ball', pl: 'piłka', hint: 'sport' },
  { en: 'balloon', pl: 'balon', hint: 'powietrzny' },
  { en: 'bandage', pl: 'bandaż', hint: 'rana' },
  { en: 'banner', pl: 'baner', hint: 'flaga' },
  { en: 'barrel', pl: 'beczka', hint: 'drewno' },
  { en: 'basket', pl: 'koszyk', hint: 'piknik' },
  { en: 'bat', pl: 'kij', hint: 'baseball' },
  { en: 'battery', pl: 'bateria', hint: 'energia' },
  { en: 'bed', pl: 'łóżko', hint: 'spanie' },
  { en: 'bell', pl: 'dzwonek', hint: 'dźwięk' },
  { en: 'belt', pl: 'pasek', hint: 'talią' },
  { en: 'bench', pl: 'ławka', hint: 'siadanie' },
  { en: 'bicycle', pl: 'rower', hint: 'pedały' },
  { en: 'binoculars', pl: 'lornetka', hint: 'powiększenie' },
  { en: 'blanket', pl: 'koc', hint: 'ciepło' },
  { en: 'blocks', pl: 'klocki', hint: 'zabawy' },
  { en: 'board', pl: 'tablica', hint: 'szkoła' },
  { en: 'boat', pl: 'łódź', hint: 'woda' },
  { en: 'bomb', pl: 'bomba', hint: 'wybuch' },
  { en: 'bone', pl: 'kość', hint: 'pies' },
  { en: 'book', pl: 'książka', hint: 'czytanie' },
  { en: 'bookcase', pl: 'regał', hint: 'półki' },
  { en: 'boots', pl: 'buty', hint: 'stopa' },
  { en: 'bottle', pl: 'butelka', hint: 'napój' },
  { en: 'bow', pl: 'łuk', hint: 'strzały' },
  { en: 'bowl', pl: 'miska', hint: 'zupa' },
  { en: 'box', pl: 'pudełko', hint: 'zawartość' },
  { en: 'bracelet', pl: 'bransoletka', hint: 'złoto' },
  { en: 'branch', pl: 'gałąź', hint: 'drzewo' },
  { en: 'brick', pl: 'cegła', hint: 'budynek' },
  { en: 'bridge', pl: 'most', hint: 'rzeka' },
  { en: 'briefcase', pl: 'teczka', hint: 'praca' },
  { en: 'brush', pl: 'pędzel', hint: 'farba' },
  { en: 'bucket', pl: 'wiadro', hint: 'woda' },
  { en: 'button', pl: 'guzik', hint: 'spodnie' },
  { en: 'cabinet', pl: 'szafka', hint: 'półki' },
  { en: 'cable', pl: 'kabel', hint: 'elektryczność' },
  { en: 'cage', pl: 'klatka', hint: 'ptak' },
  { en: 'calendar', pl: 'kalendarz', hint: 'data' },
  { en: 'camera', pl: 'aparat fotograficzny', hint: 'zdjęcie' },
  { en: 'candle', pl: 'świeca', hint: 'światło' },
  { en: 'cannon', pl: 'armata', hint: 'kula' },
  { en: 'canoe', pl: 'kanu', hint: 'wiosła' },
  { en: 'cape', pl: 'peleryna', hint: 'superbohatera' },
  { en: 'car', pl: 'samochód', hint: 'droga' },
  { en: 'card', pl: 'karta', hint: 'gra' },
  { en: 'carpet', pl: 'dywan', hint: 'podłoga' },
  { en: 'carriage', pl: 'kareta', hint: 'konie' },
  { en: 'cart', pl: 'wózek', hint: 'towar' },
  { en: 'cartridge', pl: 'nabój', hint: 'broń' },
  { en: 'case', pl: 'etui', hint: 'ochrona' },
  { en: 'castle', pl: 'zamek', hint: 'warownia' },
  { en: 'chain', pl: 'łańcuch', hint: 'ogniwa' },
  { en: 'chair', pl: 'krzesło', hint: 'siadanie' },
  { en: 'chalk', pl: 'kreda', hint: 'tablica' },
  { en: 'chandelier', pl: 'żyrandol', hint: 'światło' },
  { en: 'chest', pl: 'skrzynia', hint: 'skarb' },
  { en: 'chimney', pl: 'komin', hint: 'dym' },
  { en: 'chisel', pl: 'dłuto', hint: 'drewno' },
  { en: 'church', pl: 'kościół', hint: 'modlitwa' },
  { en: 'circle', pl: 'koło', hint: 'okrąg' },
  { en: 'city', pl: 'miasto', hint: 'budynki' },
  { en: 'class', pl: 'klasa', hint: 'uczeń' },
  { en: 'classroom', pl: 'sala lekcyjna', hint: 'nauczyciel' },
  { en: 'claw', pl: 'pazur', hint: 'kocham' },
  { en: 'clay', pl: 'glina', hint: 'modelowanie' },
  { en: 'clock', pl: 'zegar', hint: 'czas' },
  { en: 'cloth', pl: 'tkanina', hint: 'ubranie' },
  { en: 'clothes', pl: 'ubrania', hint: 'odzież' },
  { en: 'cloud', pl: 'chmura', hint: 'niebo' },
  { en: 'club', pl: 'klub', hint: 'ludzie' },
  { en: 'clue', pl: 'wskazówka', hint: 'detektyw' },
  { en: 'coach', pl: 'trener', hint: 'sport' },
  { en: 'coal', pl: 'węgiel', hint: 'czarny' },
  { en: 'coast', pl: 'wybrzeże', hint: 'morze' },
  { en: 'coat', pl: 'płaszcz', hint: 'zimno' },
  { en: 'cobweb', pl: 'pajęczyna', hint: 'pająk' },
  { en: 'mountain', pl: 'góra', hint: 'wysoka' },
  { en: 'valley', pl: 'dolina', hint: 'nisko' },
  { en: 'desert', pl: 'pustynia', hint: 'piasek' },
  { en: 'island', pl: 'wyspa', hint: 'ocean' },
  { en: 'forest', pl: 'las', hint: 'drzewa' },
  { en: 'river', pl: 'rzeka', hint: 'płynie' },
  { en: 'beach', pl: 'plaża', hint: 'słońce' },
  { en: 'volcano', pl: 'wulkan', hint: 'lawa' },
  { en: 'cave', pl: 'jaskinia', hint: 'ciemno' },
  { en: 'swamp', pl: 'bagno', hint: 'mokro' },
  { en: 'garden', pl: 'ogród', hint: 'kwiaty' },
  { en: 'stadium', pl: 'stadion', hint: 'mecz' },
  { en: 'airport', pl: 'lotnisko', hint: 'samolot' },
  { en: 'theatre', pl: 'teatr', hint: 'aktor' },
  { en: 'library', pl: 'biblioteka', hint: 'cisza' },
  { en: 'hospital', pl: 'szpital', hint: 'zdrowie' },
  { en: 'bridge', pl: 'most', hint: 'rzeka' },
  { en: 'factory', pl: 'fabryka', hint: 'produkcja' },
  { en: 'museum', pl: 'muzeum', hint: 'sztuka' },

  // Countries
  { en: 'Poland', pl: 'Polska', hint: 'Warszawa' },
  { en: 'Germany', pl: 'Niemcy', hint: 'Berlin' },
  { en: 'France', pl: 'Francja', hint: 'Paryż' },
  { en: 'Spain', pl: 'Hiszpania', hint: 'Madryt' },
  { en: 'Italy', pl: 'Włochy', hint: 'Rzym' },
  { en: 'Japan', pl: 'Japonia', hint: 'Tokio' },
  { en: 'China', pl: 'Chiny', hint: 'Pekin' },
  { en: 'Brazil', pl: 'Brazylia', hint: 'kawa' },
  { en: 'Egypt', pl: 'Egipt', hint: 'piramidy' },
  { en: 'Norway', pl: 'Norwegia', hint: 'zimno' },
  { en: 'Canada', pl: 'Kanada', hint: 'klon' },
  { en: 'Mexico', pl: 'Meksyk', hint: 'taco' },

  // Technology & Digital
  { en: 'computer', pl: 'komputer', hint: 'ekran' },
  { en: 'keyboard', pl: 'klawiatura', hint: 'pisanie' },
  { en: 'laptop', pl: 'laptop', hint: 'przenośny' },
  { en: 'printer', pl: 'drukarka', hint: 'papier' },
  { en: 'mouse', pl: 'myszka', hint: 'klik' },
  { en: 'robot', pl: 'robot', hint: 'metal' },
  { en: 'drone', pl: 'dron', hint: 'latanie' },
  { en: 'satellite', pl: 'satelita', hint: 'kosmos' },
  { en: 'rocket', pl: 'rakieta', hint: 'księżyc' },
  { en: 'phone', pl: 'telefon', hint: 'dzwoni' },
  { en: 'tablet', pl: 'tablet', hint: 'dotyk' },
  { en: 'internet', pl: 'internet', hint: 'sieć' },
  { en: 'password', pl: 'hasło', hint: 'sekret' },
  { en: 'camera', pl: 'aparat', hint: 'zdjęcie' },
  { en: 'engine', pl: 'silnik', hint: 'auto' },
  { en: 'laser', pl: 'laser', hint: 'światło' },
  { en: 'microscope', pl: 'mikroskop', hint: 'małe' },

  // People & Roles
  { en: 'pilot', pl: 'pilot', hint: 'niebo' },
  { en: 'doctor', pl: 'lekarz', hint: 'fartuch' },
  { en: 'teacher', pl: 'nauczyciel', hint: 'szkoła' },
  { en: 'soldier', pl: 'żołnierz', hint: 'mundur' },
  { en: 'chef', pl: 'szef kuchni', hint: 'gotowanie' },
  { en: 'artist', pl: 'artysta', hint: 'pędzel' },
  { en: 'dentist', pl: 'dentysta', hint: 'zęby' },
  { en: 'farmer', pl: 'rolnik', hint: 'pole' },
  { en: 'king', pl: 'król', hint: 'korona' },
  { en: 'queen', pl: 'królowa', hint: 'pałac' },
  { en: 'knight', pl: 'rycerz', hint: 'zbroja' },
  { en: 'detective', pl: 'detektyw', hint: 'lupa' },
  { en: 'neighbor', pl: 'sąsiad', hint: 'dom' },
  { en: 'stranger', pl: 'nieznajomy', hint: 'obcy' },

  // Famous People (Roles/Titles)
  { en: 'Einstein', pl: 'Einstein', hint: 'geniusz' },
  { en: 'Shakespeare', pl: 'Szekspir', hint: 'pisarz' },
  { en: 'Da Vinci', pl: 'Da Vinci', hint: 'malarz' },
  { en: 'Mozart', pl: 'Mozart', hint: 'muzyka' },
  { en: 'Cleopatra', pl: 'Kleopatra', hint: 'Nil' },
  { en: 'Columbus', pl: 'Kolumb', hint: 'odkrywca' },
  { en: 'Newton', pl: 'Newton', hint: 'jabłko' },

  // Everyday Objects (More Variety)
  { en: 'comb', pl: 'grzebień', hint: 'włosy' },
  { en: 'mirror', pl: 'lustro', hint: 'twarz' },
  { en: 'soap', pl: 'mydło', hint: 'kąpiel' },
  { en: 'towel', pl: 'ręcznik', hint: 'suchy' },
  { en: 'wallet', pl: 'portfel', hint: 'pieniądze' },
  { en: 'key', pl: 'klucz', hint: 'zamek' },
  { en: 'hammer', pl: 'młotek', hint: 'gwóźdź' },
  { en: 'ladder', pl: 'drabina', hint: 'wysoko' },
  { en: 'compass', pl: 'kompas', hint: 'północ' },
  { en: 'clock', pl: 'zegar', hint: 'godzina' },
  { en: 'candle', pl: 'świeca', hint: 'ogień' },
  { en: 'vase', pl: 'wazon', hint: 'kwiaty' },
  { en: 'lamp', pl: 'lampa', hint: 'jasno' },
  { en: 'pillow', pl: 'poduszka', hint: 'miękka' },
  { en: 'curtain', pl: 'zasłona', hint: 'okno' },
  { en: 'carpet', pl: 'dywan', hint: 'podłoga' },
  { en: 'brush', pl: 'szczotka', hint: 'czyszczenie' },
  { en: 'envelope', pl: 'koperta', hint: 'list' },
  { en: 'paper', pl: 'papier', hint: 'pisanie' },
  { en: 'scissors', pl: 'nożyczki', hint: 'ciąć' },
  { en: 'umbrella', pl: 'parasol', hint: 'deszcz' },
  { en: 'whistle', pl: 'gwizdek', hint: 'trener' },
  { en: 'magnet', pl: 'magnes', hint: 'metal' },

  // Nature & Weather
  { en: 'thunder', pl: 'grzmot', hint: 'burza' },
  { en: 'lightning', pl: 'błyskawica', hint: 'niebo' },
  { en: 'rainbow', pl: 'tęcza', hint: 'kolory' },
  { en: 'star', pl: 'gwiazda', hint: 'noc' },
  { en: 'moon', pl: 'księżyc', hint: 'jasny' },
  { en: 'planet', pl: 'planeta', hint: 'ziemia' },
  { en: 'ocean', pl: 'ocean', hint: 'duży' },
  { en: 'wave', pl: 'fala', hint: 'surfing' },
  { en: 'leaf', pl: 'liść', hint: 'drzewo' },
  { en: 'flower', pl: 'kwiat', hint: 'zapach' },
  { en: 'stone', pl: 'kamień', hint: 'twardy' },
  { en: 'sand', pl: 'piasek', hint: 'pustynia' },
  { en: 'snow', pl: 'śnieg', hint: 'bałwan' },
  { en: 'rain', pl: 'deszcz', hint: 'mokro' },
  { en: 'wind', pl: 'wiatr', hint: 'wieje' },
  // Transportation
  { en: 'airplane', pl: 'samolot', hint: 'chmury' },
  { en: 'bus', pl: 'autobus', hint: 'przystanek' },
  { en: 'train', pl: 'pociąg', hint: 'tory' },
  { en: 'truck', pl: 'ciężarówka', hint: 'dostawa' },
  { en: 'submarine', pl: 'łódź podwodna', hint: 'głęboko' },
  { en: 'scooter', pl: 'hulajnoga', hint: 'koła' },
  { en: 'helicopter', pl: 'helikopter', hint: 'śmigło' },
  { en: 'tram', pl: 'tramwaj', hint: 'szyny' },
  { en: 'ship', pl: 'statek', hint: 'port' },
  { en: 'tractor', pl: 'traktor', hint: 'wieś' },

  // Clothing & Accessories
  { en: 'shirt', pl: 'koszula', hint: 'guziki' },
  { en: 'pants', pl: 'spodnie', hint: 'nogi' },
  { en: 'hat', pl: 'czapka', hint: 'głowa' },
  { en: 'scarf', pl: 'szalik', hint: 'szyja' },
  { en: 'gloves', pl: 'rękawiczki', hint: 'palce' },
  { en: 'jacket', pl: 'kurtka', hint: 'zima' },
  { en: 'dress', pl: 'sukienka', hint: 'kobieta' },
  { en: 'tie', pl: 'krawat', hint: 'garnitur' },
  { en: 'skirt', pl: 'spódnica', hint: 'krótka' },
  { en: 'vest', pl: 'kamizelka', hint: 'bez rękawów' },

  // Body Parts
  { en: 'brain', pl: 'mózg', hint: 'myślenie' },
  { en: 'heart', pl: 'serce', hint: 'bicie' },
  { en: 'eye', pl: 'oko', hint: 'patrzeć' },
  { en: 'ear', pl: 'ucho', hint: 'słuchać' },
  { en: 'mouth', pl: 'usta', hint: 'mówić' },
  { en: 'hand', pl: 'ręka', hint: 'trzymać' },
  { en: 'foot', pl: 'stopa', hint: 'chodzić' },
  { en: 'finger', pl: 'palec', hint: 'wskazywać' },
  { en: 'knee', pl: 'kolano', hint: 'noga' },
  { en: 'shoulder', pl: 'ramię', hint: 'plecak' },

  // Space & Science
  { en: 'telescope', pl: 'teleskop', hint: 'gwiazdy' },
  { en: 'galaxy', pl: 'galaktyka', hint: 'mleczna' },
  { en: 'asteroid', pl: 'asteroida', hint: 'skała' },
  { en: 'comet', pl: 'kometa', hint: 'ogon' },
  { en: 'oxygen', pl: 'tlen', hint: 'oddech' },
  { en: 'atom', pl: 'atom', hint: 'mały' },
  { en: 'gravity', pl: 'grawitacja', hint: 'ziemia' },
  { en: 'laboratory', pl: 'laboratorium', hint: 'test' },
  { en: 'chemist', pl: 'chemik', hint: 'mikstura' },
  { en: 'astronomy', pl: 'astronomia', hint: 'niebo' },

  // More Countries & Places
  { en: 'Greece', pl: 'Grecja', hint: 'bogowie' },
  { en: 'Sweden', pl: 'Szwecja', hint: 'północ' },
  { en: 'Portugal', pl: 'Portugalia', hint: 'ocean' },
  { en: 'Turkey', pl: 'Turcja', hint: 'kebab' },
  { en: 'Austria', pl: 'Austria', hint: 'Alpy' },
  { en: 'Switzerland', pl: 'Szwajcaria', hint: 'zegarki' },
  { en: 'Ireland', pl: 'Irlandia', hint: 'zielona' },
  { en: 'Denmark', pl: 'Dania', hint: 'lego' },
  { en: 'Thailand', pl: 'Tajlandia', hint: 'Azja' },
  { en: 'Vietnam', pl: 'Wietnam', hint: 'ryż' },

  // Music & Arts
  { en: 'guitar', pl: 'gitara', hint: 'struny' },
  { en: 'piano', pl: 'pianino', hint: 'klawisze' },
  { en: 'drums', pl: 'perkusja', hint: 'rytm' },
  { en: 'violin', pl: 'skrzypce', hint: 'smyczek' },
  { en: 'trumpet', pl: 'trąbka', hint: 'dmuchać' },
  { en: 'canvas', pl: 'płótno', hint: 'obraz' },
  { en: 'sculpture', pl: 'rzeźba', hint: 'kamień' },
  { en: 'gallery', pl: 'galeria', hint: 'sztuka' },
  { en: 'concert', pl: 'koncert', hint: 'muzyka' },
  { en: 'fame', pl: 'sława', hint: 'gwiazda' },

  // Office & Stationery
  { en: 'folder', pl: 'folder', hint: 'dokumenty' },
  { en: 'staple', pl: 'zszywka', hint: 'papier' },
  { en: 'glue', pl: 'klej', hint: 'łączyć' },
  { en: 'eraser', pl: 'gumka', hint: 'błąd' },
  { en: 'ruler', pl: 'linijka', hint: 'mierzyć' },
  { en: 'desk', pl: 'biurko', hint: 'praca' },
  { en: 'notebook', pl: 'notatnik', hint: 'zapiski' },
  { en: 'calculator', pl: 'kalkulator', hint: 'liczby' },
  { en: 'clip', pl: 'spinacz', hint: 'metalowy' },
  { en: 'pen', pl: 'długopis', hint: 'tusz' },

  // Professions
  { en: 'lawyer', pl: 'prawnik', hint: 'prawo' },
  { en: 'plumber', pl: 'hydraulik', hint: 'rura' },
  { en: 'builder', pl: 'budowniczy', hint: 'dom' },
  { en: 'waiter', pl: 'kelner', hint: 'talerz' },
  { en: 'baker', pl: 'piekarz', hint: 'chleb' },
  { en: 'mechanic', pl: 'mechanik', hint: 'naprawa' },
  { en: 'actor', pl: 'aktor', hint: 'film' },
  { en: 'singer', pl: 'piosenkarz', hint: 'mikrofon' },
  { en: 'nurse', pl: 'pielęgniarka', hint: 'zastrzyk' },
  { en: 'firefighter', pl: 'strażak', hint: 'ogień' },

  // Sports & Hobbies
  { en: 'tennis', pl: 'tenis', hint: 'rakieta' },
  { en: 'soccer', pl: 'piłka nożna', hint: 'bramka' },
  { en: 'swimming', pl: 'pływanie', hint: 'basen' },
  { en: 'chess', pl: 'szachy', hint: 'figury' },
  { en: 'boxing', pl: 'boks', hint: 'rękawice' },
  { en: 'hiking', pl: 'wędrówka', hint: 'plecak' },
  { en: 'skating', pl: 'łyżwiarstwo', hint: 'lód' },
  { en: 'yoga', pl: 'joga', hint: 'mata' },
  { en: 'fishing', pl: 'wędkarstwo', hint: 'wędka' },
  { en: 'running', pl: 'bieganie', hint: 'buty' },

  // Misc
  { en: 'money', pl: 'pieniądze', hint: 'bank' },
  { en: 'ticket', pl: 'bilet', hint: 'wjazd' },
  { en: 'gift', pl: 'prezent', hint: 'kokarda' },
  { en: 'shadow', pl: 'cień', hint: 'słońce' },
  { en: 'voice', pl: 'głos', hint: 'gardło' },
  { en: 'dream', pl: 'sen', hint: 'noc' },
  { en: 'peace', pl: 'pokój', hint: 'gołąb' },
  { en: 'light', pl: 'światło', hint: 'lampa' },
  { en: 'sound', pl: 'dźwięk', hint: 'ucho' },
  { en: 'truth', pl: 'prawda', hint: 'szczerość' },

  // Household & Furniture
  { en: 'sofa', pl: 'kanapa', hint: 'salon' },
  { en: 'wardrobe', pl: 'szafa', hint: 'ubrania' },
  { en: 'drawer', pl: 'szuflada', hint: 'otwierać' },
  { en: 'sink', pl: 'zlewozmywak', hint: 'kuchnia' },
  { en: 'shower', pl: 'prysznic', hint: 'łazienka' },
  { en: 'toilet', pl: 'toaleta', hint: 'papier' },
  { en: 'stove', pl: 'kuchenka', hint: 'gotować' },
  { en: 'microwave', pl: 'mikrofalówka', hint: 'szybko' },
  { en: 'toaster', pl: 'toster', hint: 'grzanka' },
  { en: 'blender', pl: 'blender', hint: 'koktajl' },

  // Architecture & Construction
  { en: 'roof', pl: 'dach', hint: 'góra' },
  { en: 'wall', pl: 'ściana', hint: 'obraz' },
  { en: 'floor', pl: 'podłoga', hint: 'dywan' },
  { en: 'stairs', pl: 'schody', hint: 'wchodzić' },
  { en: 'balcony', pl: 'balkon', hint: 'widok' },
  { en: 'ceiling', pl: 'sufit', hint: 'żyrandol' },
  { en: 'basement', pl: 'piwnica', hint: 'nisko' },
  { en: 'garage', pl: 'garaż', hint: 'auto' },
  { en: 'fence', pl: 'płot', hint: 'ogród' },
  { en: 'gate', pl: 'brama', hint: 'wejście' },

  // Nature (Detailed)
  { en: 'moss', pl: 'mech', hint: 'miękki' },
  { en: 'trunk', pl: 'pień', hint: 'drzewo' },
  { en: 'root', pl: 'korzeń', hint: 'ziemia' },
  { en: 'seed', pl: 'nasiono', hint: 'sadzić' },
  { en: 'petal', pl: 'płatek', hint: 'kwiat' },
  { en: 'cliff', pl: 'klif', hint: 'wysoki' },
  { en: 'valley', pl: 'dolina', hint: 'między górami' },
  { en: 'canyon', pl: 'kanion', hint: 'głęboki' },
  { en: 'stream', pl: 'strumień', hint: 'woda' },
  { en: 'pond', pl: 'staw', hint: 'żaby' },

  // Occupations (More Variety)
  { en: 'librarian', pl: 'bibliotekarz', hint: 'książki' },
  { en: 'barista', pl: 'barista', hint: 'kawa' },
  { en: 'welder', pl: 'spawacz', hint: 'iskry' },
  { en: 'electrician', pl: 'elektryk', hint: 'prąd' },
  { en: 'architect', pl: 'architekt', hint: 'projekt' },
  { en: 'surgeon', pl: 'chirurg', hint: 'operacja' },
  { en: 'carpenter', pl: 'stolarz', hint: 'drewno' },
  { en: 'janitor', pl: 'dozorca', hint: 'sprzątać' },
  { en: 'tailor', pl: 'krawiec', hint: 'szycie' },
  { en: 'sailor', pl: 'marynarz', hint: 'morze' },

  // Famous Figures (More Categories)
  { en: 'Beethoven', pl: 'Beethoven', hint: 'pianino' },
  { en: 'Picasso', pl: 'Picasso', hint: 'sztuka' },
  { en: 'Darwin', pl: 'Darwin', hint: 'ewolucja' },
  { en: 'Aristotle', pl: 'Arystoteles', hint: 'filozof' },
  { en: 'Tesla', pl: 'Tesla', hint: 'prąd' },
  { en: 'Ghandi', pl: 'Ghandi', hint: 'pokój' },
  { en: 'Socrates', pl: 'Sokrates', hint: 'pytania' },
  { en: 'Earhart', pl: 'Earhart', hint: 'lotnik' },
  { en: 'Copernicus', pl: 'Kopernik', hint: 'astronom' },
  { en: 'Mandela', pl: 'Mandela', hint: 'wolność' },

  // Modern Technology
  { en: 'server', pl: 'serwer', hint: 'dane' },
  { en: 'router', pl: 'router', hint: 'wifi' },
  { en: 'processor', pl: 'procesor', hint: 'chip' },
  { en: 'touchscreen', pl: 'ekran dotykowy', hint: 'palec' },
  { en: 'algorithm', pl: 'algorytm', hint: 'logika' },
  { en: 'pixel', pl: 'piksel', hint: 'obraz' },
  { en: 'firewall', pl: 'zapora', hint: 'ochrona' },
  { en: 'avatar', pl: 'awatar', hint: 'profil' },
  { en: 'database', pl: 'baza danych', hint: 'informacje' },
  { en: 'webcam', pl: 'kamerka', hint: 'wideo' },

  // Geography & Countries
  { en: 'Australia', pl: 'Australia', hint: 'kangur' },
  { en: 'Belgium', pl: 'Belgia', hint: 'czekolada' },
  { en: 'Finland', pl: 'Finlandia', hint: 'sauna' },
  { en: 'Iceland', pl: 'Islandia', hint: 'gejzery' },
  { en: 'Kenya', pl: 'Kenia', hint: 'Afryka' },
  { en: 'Morocco', pl: 'Maroko', hint: 'pustynia' },
  { en: 'Netherlands', pl: 'Holandia', hint: 'tulipany' },
  { en: 'Peru', pl: 'Peru', hint: 'góry' },
  { en: 'Russia', pl: 'Rosja', hint: 'zimno' },
  { en: 'Sweden', pl: 'Szwecja', hint: 'północ' },

  // Abstract Nouns
  { en: 'history', pl: 'historia', hint: 'przeszłość' },
  { en: 'science', pl: 'nauka', hint: 'wiedza' },
  { en: 'health', pl: 'zdrowie', hint: 'ciało' },
  { en: 'wealth', pl: 'bogactwo', hint: 'pieniądze' },
  { en: 'power', pl: 'siła', hint: 'energia' },
  { en: 'justice', pl: 'sprawiedliwość', hint: 'sąd' },
  { en: 'freedom', pl: 'wolność', hint: 'ptak' },
  { en: 'fear', pl: 'strach', hint: 'ciemność' },
  { en: 'joy', pl: 'radość', hint: 'uśmiech' },
  { en: 'luck', pl: 'szczęście', hint: 'los' },

  // Animals (Exotic/Specific)
  { en: 'sloth', pl: 'leniwiec', hint: 'wolny' },
  { en: 'ostrich', pl: 'struś', hint: 'biegać' },
  { en: 'flamingo', pl: 'flaming', hint: 'różowy' },
  { en: 'platypus', pl: 'dziobak', hint: 'dziwny' },
  { en: 'raccoon', pl: 'szop', hint: 'maska' },
  { en: 'llama', pl: 'lama', hint: 'pluć' },
  { en: 'manta', pl: 'manta', hint: 'ocean' },
  { en: 'beetle', pl: 'chrząszcz', hint: 'owad' },
  { en: 'wasp', pl: 'osa', hint: 'żądło' },
  { en: 'mole', pl: 'kret', hint: 'ziemia' },

  // Miscellaneous Tools & Objects
  { en: 'funnel', pl: 'lejka', hint: 'płyn' },
  { en: 'pliers', pl: 'kombinerki', hint: 'ściskać' },
  { en: 'wrench', pl: 'klucz francuski', hint: 'śruba' },
  { en: 'microchip', pl: 'mikroczip', hint: 'elektronika' },
  { en: 'lens', pl: 'soczewka', hint: 'okulary' },
  { en: 'shutter', pl: 'migawka', hint: 'aparat' },
  { en: 'prism', pl: 'pryzmat', hint: 'kolory' },
  { en: 'gears', pl: 'zębatki', hint: 'zegar' },
  { en: 'pulley', pl: 'kołowrotek', hint: 'lina' },
  { en: 'spring', pl: 'sprężyna', hint: 'skakać' },
  // Materials & Elements
  { en: 'gold', pl: 'złoto', hint: 'żółte' },
  { en: 'silver', pl: 'srebro', hint: 'moneta' },
  { en: 'iron', pl: 'żelazo', hint: 'twarde' },
  { en: 'copper', pl: 'miedź', hint: 'drut' },
  { en: 'plastic', pl: 'plastik', hint: 'butelka' },
  { en: 'glass', pl: 'szkło', hint: 'okno' },
  { en: 'wood', pl: 'drewno', hint: 'las' },
  { en: 'rubber', pl: 'guma', hint: 'opona' },
  { en: 'leather', pl: 'skóra', hint: 'pasek' },
  { en: 'cotton', pl: 'bawełna', hint: 'miękka' },

  // Space & Astronomy
  { en: 'nebula', pl: 'mgławica', hint: 'chmura' },
  { en: 'meteor', pl: 'meteor', hint: 'spadająca gwiazda' },
  { en: 'orbit', pl: 'orbita', hint: 'droga' },
  { en: 'vacuum', pl: 'próżnia', hint: 'kosmos' },
  { en: 'capsule', pl: 'kapsuła', hint: 'powrót' },
  { en: 'Mars', pl: 'Mars', hint: 'czerwony' },
  { en: 'Jupiter', pl: 'Jowisz', hint: 'olbrzym' },
  { en: 'Saturn', pl: 'Saturn', hint: 'pierścienie' },
  { en: 'Venus', pl: 'Wenus', hint: 'gorąca' },
  { en: 'Mercury', pl: 'Merkury', hint: 'blisko słońca' },
  // Specialized Professions
  { en: 'geologist', pl: 'geolog', hint: 'skały' },
  { en: 'lawyer', pl: 'prawnik', hint: 'prawo' },
  { en: 'biologist', pl: 'biolog', hint: 'życie' },
  { en: 'psychologist', pl: 'psycholog', hint: 'umysł' },
  { en: 'diver', pl: 'nurek', hint: 'głębokość' },
  { en: 'referee', pl: 'sędzia', hint: 'gwizdek' },
  { en: 'photographer', pl: 'fotograf', hint: 'zdjęcia' },
  { en: 'translator', pl: 'tłumacz', hint: 'język' },
  { en: 'accountant', pl: 'księgowy', hint: 'podatki' },
  { en: 'editor', pl: 'redaktor', hint: 'tekst' },
  // Advanced Tech & Hardware
  { en: 'sensor', pl: 'czujnik', hint: 'ruch' },
  { en: 'fiber', pl: 'światłowód', hint: 'szybki' },
  { en: 'headset', pl: 'słuchawki', hint: 'uszy' },
  { en: 'joystick', pl: 'dżojstik', hint: 'gra' },
  { en: 'modem', pl: 'modem', hint: 'sygnał' },
  { en: 'scanner', pl: 'skaner', hint: 'kopia' },
  { en: 'battery', pl: 'bateria', hint: 'prąd' },
  { en: 'drone', pl: 'dron', hint: 'śmigła' },
  { en: 'hologram', pl: 'hologram', hint: 'światło' },
  { en: 'nanotechnology', pl: 'nanotechnologia', hint: 'mikro' },
  // Emotions & Concepts
  { en: 'wisdom', pl: 'mądrość', hint: 'sowa' },
  { en: 'energy', pl: 'energia', hint: 'ruch' },
  { en: 'beauty', pl: 'piękno', hint: 'kwiat' },
  { en: 'safety', pl: 'bezpieczeństwo', hint: 'kask' },
  { en: 'danger', pl: 'niebezpieczeństwo', hint: 'trójkąt' },
  { en: 'honor', pl: 'honor', hint: 'rycerz' },
  { en: 'trust', pl: 'zaufanie', hint: 'przyjaciel' },
  { en: 'memory', pl: 'pamięć', hint: 'głowa' },
  { en: 'rhythm', pl: 'rytm', hint: 'muzyka' },
  { en: 'future', pl: 'przyszłość', hint: 'jutro' },

  // Miscellaneous Household
  { en: 'needle', pl: 'igła', hint: 'szycie' },
  { en: 'thread', pl: 'nić', hint: 'kolorowa' },
  { en: 'plug', pl: 'wtyczka', hint: 'gniazdko' },
  { en: 'shampoo', pl: 'szampon', hint: 'włosy' },
  { en: 'sponge', pl: 'gąbka', hint: 'mycie' },
  { en: 'comb', pl: 'grzebień', hint: 'fryzura' },
  { en: 'perfume', pl: 'perfumy', hint: 'zapach' },
  { en: 'tray', pl: 'taca', hint: 'kelner' },
  { en: 'pot', pl: 'garnek', hint: 'gotowanie' },
  { en: 'kettle', pl: 'czajnik', hint: 'herbata' },

  // Sport & Outdoor
  { en: 'racket', pl: 'rakieta', hint: 'tenis' },
  { en: 'helmet', pl: 'kask', hint: 'rower' },
  { en: 'trophy', pl: 'puchar', hint: 'zwycięzca' },
  { en: 'whistle', pl: 'gwizdek', hint: 'trener' },
  { en: 'goggles', pl: 'gogle', hint: 'narty' },
  { en: 'compass', pl: 'kompas', hint: 'północ' },
  { en: 'tent', pl: 'namiot', hint: 'biwak' },
  { en: 'parachute', pl: 'spadochron', hint: 'skok' },
  { en: 'skis', pl: 'narty', hint: 'śnieg' },
  { en: 'stadium', pl: 'stadion', hint: 'kibice' },

  // Time & Measurement
  { en: 'century', pl: 'wiek', hint: 'sto lat' },
  { en: 'second', pl: 'sekunda', hint: 'krótka' },
  { en: 'calendar', pl: 'kalendarz', hint: 'daty' },
  { en: 'degree', pl: 'stopień', hint: 'ciepło' },
  { en: 'meter', pl: 'metr', hint: 'długość' },
  { en: 'weight', pl: 'waga', hint: 'kilogram' },
  { en: 'clock', pl: 'zegar', hint: 'godzina' },
  { en: 'autumn', pl: 'jesień', hint: 'liście' },
  { en: 'winter', pl: 'zima', hint: 'lód' },
  { en: 'spring', pl: 'wiosna', hint: 'kwiaty' },
];