import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  mainTitle: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 50,
    marginTop: 30,
    textAlign: 'center',
  },
  title: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 40,
    textAlign: 'center',
  },
  largeButton: {
    backgroundColor: '#fff',
    paddingVertical: 24,
    paddingHorizontal: 48,
    borderRadius: 12,
    marginTop: 20,
    marginBottom: 30,
    width: 250,
    alignSelf: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  largeButtonText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#7c3aed',
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#fff',
    paddingVertical: 16,
    paddingHorizontal: 48,
    borderRadius: 12,
    marginTop: 20,
    elevation: 5,
  },
  buttonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#7c3aed',
    textAlign: 'center',
  },
  counterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 40,
    gap: 6,
  },
  counterButton: {
    backgroundColor: '#fff',
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  counterButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#7c3aed',
  },
  counterDisplay: {
    backgroundColor: '#1e1b4b',
    width: 60,
    paddingVertical: 6,
    paddingHorizontal: 6,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  counterText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  optionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 40,
    width: '80%',
  },
  optionText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  optionsWrapper: {
    flex: 1,
    flexDirection: 'column',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  codeDisplay: {
    backgroundColor: '#1e1b4b',
    paddingVertical: 32,
    paddingHorizontal: 48,
    borderRadius: 12,
    marginBottom: 40,
    minWidth: 300,
    justifyContent: 'center',
    alignItems: 'center',
  },
  codeText: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
  },
  impostorText: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#fca5a5',
  },
  hintText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fca5a5',
    marginTop: 16,
    textAlign: 'center',
  },
  resultContainer: {
    marginBottom: 40,
  },
  resultText: {
    fontSize: 24,
    color: '#fff',
    marginBottom: 16,
    textAlign: 'center',
  },
  impostorNumberText: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#fca5a5',
    textAlign: 'center',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  resultButton: {
    marginTop: 10,
    backgroundColor: '#fff',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  resultButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#7c3aed',
    textAlign: 'center',
  },
  namesContainer: {
    width: '100%',
    marginBottom: 20,
    paddingHorizontal: 20,
    maxHeight: 300,
  },
  nameInputWrapper: {
    marginBottom: 16,
  },
  playerLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 6,
  },
  nameInput: {
    backgroundColor: '#fff',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    fontSize: 16,
    color: '#333',
  },
  nameInputText: {
    fontSize: 16,
    color: '#333',
  },
});

export default styles;